New log file opened at Tue Jan 31 15:44:26 COT 2017 by 1032@DESKTOP-EUGFD9N
Taking next connection to: 52538
New client attempting to connect on port: 52539-52538
  Address = /192.168.0.2:52538
This client on port 52539 has uuid 9ad4e20d-0a57-4980-a9c4-603800b09b7b configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-9ad4e20d-0a57-4980-a9c4-603800b09b7b
Taking next connection to: 52538
New client attempting to connect on port: 52540-52538
  Address = /192.168.0.2:52538
Handshake exception on socket: 52540
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52538
New client attempting to connect on port: 52541-52538
  Address = /192.168.0.2:52538
This client on port 52541 has uuid 8907194c-7c2b-493d-94ff-eae9d28c214c configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-9ad4e20d-0a57-4980-a9c4-603800b09b7b, activator-8907194c-7c2b-493d-94ff-eae9d28c214c
Taking next connection to: 52538
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52538
New client attempting to connect on port: 52566-52538
  Address = /192.168.0.2:52538
Handshake exception on socket: 52566
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 52538
New client attempting to connect on port: 52567-52538
  Address = /192.168.0.2:52538
This client on port 52567 has uuid da582a29-87a4-4d43-abaf-47c3d8876ff4 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-9ad4e20d-0a57-4980-a9c4-603800b09b7b, play-fork-run-da582a29-87a4-4d43-abaf-47c3d8876ff4
Taking next connection to: 52538
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 52538
